/**
 * Locale-aware resolution of a guide topic: title, description and body.
 *
 * The project ships guide translations for 13 locales, but the language
 * switcher is gated (i18nStore, LANGUAGE_SWITCHER_ENABLED), so in production
 * this resolver takes the English path.
 *
 * Serving contract: WHOLE UNITS, NEVER A SPLICE. A reader gets either the
 * locale's title + description + body together, or the current English
 * title + description + body together:
 *   - the locale carries a whole unit and it is current  -> translated
 *   - it carries a whole unit, but the English changed after it was
 *     translated (or the pin cannot be verified)        -> current English,
 *                                                            with the older
 *                                                            translation as the
 *                                                            alternate
 *   - it does not carry a whole unit                     -> English, no alternate
 *   - English                                            -> English; no locale
 *                                                            module or status
 *                                                            table is loaded
 * "Current" comes from ./translation-status.ts, generated by
 * scripts/i18n/emit-guide-status.mjs from the history-anchored drift classifier.
 * `prefer: "translation"` is the reader's one-tap choice to read the older
 * translation of a stale topic; it never un-splices anything, it only picks
 * which of two whole units to serve.
 */
import type { Language } from "@/stores/i18nStore";
import { GUIDE_TOPICS } from "./topics";
import { GUIDE_CATEGORIES } from "./categories";
import type { GuideTranslationStatus, GuideTranslationStatusTable } from "./translation-status";

export type TopicUnit = {
  title: string;
  description: string;
  body: string;
};

/** "source": English itself. "absent": the locale has no whole unit for this topic. */
export type TopicUnitStatus = "source" | "fresh" | GuideTranslationStatus | "absent";

export type TopicUnitResolution = TopicUnit & {
  /** Which whole unit is being served. */
  unit: "translated" | "canonical";
  status: TopicUnitStatus;
  /** The other whole unit the reader may switch to, or null when there is none worth offering. */
  alternate: "translation" | "canonical" | null;
};

export type TopicUnitPreference = "translation" | "canonical";

type LocaleTopicsModule = {
  topics: Record<string, { title?: string; description?: string }>;
};

type LocaleContentModule = {
  content: Record<string, string>;
};

export type TopicUnitLoaders = {
  topics: (lang: Language) => Promise<LocaleTopicsModule | null>;
  content: (lang: Language, categoryId: string) => Promise<LocaleContentModule | null>;
  status: () => Promise<GuideTranslationStatusTable>;
};

// Per-locale module memo caches. Each key resolves to a thunk that returns
// the already-loaded module, so a given locale/category file is imported
// (and its promise settled) at most once across the process.
const localeTopicsModules: Record<string, () => Promise<LocaleTopicsModule>> = {};
const localeContentModules: Record<string, () => Promise<LocaleContentModule>> = {};

// Load a locale's topics.ts via a plain template-literal dynamic import.
// The path is statically analyzable enough for Turbopack to emit one chunk
// per locale directory; a missing/failed import (locale not yet translated)
// is swallowed and the caller serves English. The resolved module is
// memoized into localeTopicsModules so repeat lookups skip the import.
async function loadLocaleTopics(lang: Language): Promise<LocaleTopicsModule | null> {
  if (lang === "en") return null;
  if (!localeTopicsModules[lang]) {
    try {
      const mod = (await import(`./locales/${lang}/topics`)) as LocaleTopicsModule;
      localeTopicsModules[lang] = async () => mod;
      return mod;
    } catch {
      return null;
    }
  }
  return localeTopicsModules[lang]();
}

async function loadLocaleContent(
  lang: Language,
  categoryId: string,
): Promise<LocaleContentModule | null> {
  if (lang === "en") return null;
  const key = `${lang}::${categoryId}`;
  if (!localeContentModules[key]) {
    try {
      const mod = (await import(`./locales/${lang}/content/${categoryId}`)) as LocaleContentModule;
      localeContentModules[key] = async () => mod;
      return mod;
    } catch {
      return null;
    }
  }
  return localeContentModules[key]();
}

// The status table is imported lazily too, so English readers never download it.
async function loadStatusTable(): Promise<GuideTranslationStatusTable> {
  return (await import("./translation-status")).GUIDE_TRANSLATION_STATUS;
}

const DEFAULT_LOADERS: TopicUnitLoaders = {
  topics: loadLocaleTopics,
  content: loadLocaleContent,
  status: loadStatusTable,
};

/**
 * Resolve one whole, freshness-checked unit for a topic in `lang`.
 *
 * `english` is the current English unit; the caller (the topic page) already
 * has the body loaded, so it is passed in rather than re-fetched.
 */
export async function resolveTopicUnit(
  lang: Language,
  topicId: string,
  english: TopicUnit,
  opts: { prefer?: TopicUnitPreference; loaders?: Partial<TopicUnitLoaders> } = {},
): Promise<TopicUnitResolution> {
  const canonical = (status: TopicUnitStatus, alternate: "translation" | null): TopicUnitResolution => ({
    title: english.title,
    description: english.description,
    body: english.body,
    unit: "canonical",
    status,
    alternate,
  });
  if (lang === "en") return canonical("source", null);

  const topic = GUIDE_TOPICS.find((t) => t.id === topicId);
  if (!topic) return canonical("absent", null);

  const loaders = { ...DEFAULT_LOADERS, ...opts.loaders };
  const [topicsModule, contentModule, table] = await Promise.all([
    loaders.topics(lang),
    loaders.content(lang, topic.categoryId),
    loaders.status(),
  ]);
  const meta = topicsModule?.topics?.[topicId];
  const body = contentModule?.content?.[topicId];
  if (typeof meta?.title !== "string" || typeof meta.description !== "string" || typeof body !== "string") {
    return canonical("absent", null);
  }
  const translated = (status: TopicUnitStatus, alternate: "canonical" | null): TopicUnitResolution => ({
    title: meta.title as string,
    description: meta.description as string,
    body,
    unit: "translated",
    status,
    alternate,
  });

  const status = table[lang]?.[topicId];
  if (!status) return translated("fresh", null);
  return opts.prefer === "translation" ? translated(status, "canonical") : canonical(status, "translation");
}

/**
 * Resolve category name + description for the given locale, with fallback
 * to the English values in GUIDE_CATEGORIES. Category strings live in the
 * existing src/i18n/<lang>.ts files (under `guide.categories` and
 * `guide.categoryDescriptions`) — this helper exists so a single
 * locale-resolution API is available to the guide pages.
 */
export function getLocalizedCategoryFromI18n(
  categoryId: string,
  i18nCategories?: Partial<Record<string, string>>,
  i18nDescriptions?: Partial<Record<string, string>>,
): { name: string; description: string } {
  const cat = GUIDE_CATEGORIES.find((c) => c.id === categoryId);
  return {
    name: i18nCategories?.[categoryId] ?? cat?.name ?? categoryId,
    description: i18nDescriptions?.[categoryId] ?? cat?.description ?? "",
  };
}
