import { Mail, MessageSquare, Calendar } from "lucide-react";
import { Github } from "@/components/icons/brand-icons";
import type { ExamplePrompt } from "./types";

export const examples: ExamplePrompt[] = [
  {
    label: "Triage my Gmail",
    icon: Mail,
    iconColor: "#ea4335",
    prompt: "Triage my Gmail inbox and draft replies for urgent emails",
    lines: [
      { text: "Parsing instruction...", color: "text-muted-dark", delay: 400 },
      { text: "Intent detected: email_triage + auto_reply", color: "text-brand-cyan", delay: 600 },
      { text: "Selecting tools: Gmail API, NLP Classifier", color: "text-muted", delay: 500 },
      { text: "Connecting to Gmail...", color: "text-muted-dark", delay: 800 },
      { text: "Fetched 47 unread messages", color: "text-muted", delay: 600 },
      { text: "Classifying messages...", color: "text-muted-dark", delay: 700 },
      { text: "  urgent:  8  |  follow-up: 12  |  fyi: 19  |  spam: 8", color: "text-brand-emerald", delay: 500, indent: 1 },
      { text: "Drafting replies for 8 urgent emails...", color: "text-muted", delay: 900 },
      { text: "  Draft 1/8: Re: Q4 Budget Review  [ready]", color: "text-muted", delay: 300, indent: 1 },
      { text: "  Draft 2/8: Re: Production Incident  [ready]", color: "text-muted", delay: 250, indent: 1 },
      { text: "  ...6 more drafts ready", color: "text-muted-dark", delay: 200, indent: 1 },
      { text: "Done. 8 drafts saved, 8 labels applied, 8 spam archived.", color: "text-brand-emerald", delay: 500 },
    ],
  },
  {
    label: "Review this PR",
    icon: Github,
    iconColor: "#8b5cf6",
    prompt: "Review PR #142 for bugs, style issues, and missing tests",
    lines: [
      { text: "Parsing instruction...", color: "text-muted-dark", delay: 400 },
      { text: "Intent detected: code_review", color: "text-brand-cyan", delay: 600 },
      { text: "Selecting tools: GitHub API, AST Analyzer, Test Scanner", color: "text-muted", delay: 500 },
      { text: "Fetching PR #142 diff (14 files, +342 / -89)...", color: "text-muted-dark", delay: 900 },
      { text: "Analyzing code changes...", color: "text-muted-dark", delay: 800 },
      { text: "  Bug risk:     2 potential null derefs in api/handler.ts", color: "text-brand-amber", delay: 500, indent: 1 },
      { text: "  Style:        3 naming inconsistencies", color: "text-muted", delay: 400, indent: 1 },
      { text: "  Test gaps:    auth middleware untested (0% coverage)", color: "text-brand-rose", delay: 400, indent: 1 },
      { text: "Posting 6 inline review comments...", color: "text-muted", delay: 700 },
      { text: "Requesting changes with summary comment.", color: "text-muted", delay: 500 },
      { text: "Done. Review posted: 2 bugs, 3 style notes, 1 test gap.", color: "text-brand-emerald", delay: 500 },
    ],
  },
  {
    label: "Summarize Slack",
    icon: MessageSquare,
    iconColor: "#4a154b",
    prompt: "Summarize #engineering and #product channels from the last 24h",
    lines: [
      { text: "Parsing instruction...", color: "text-muted-dark", delay: 400 },
      { text: "Intent detected: channel_digest", color: "text-brand-cyan", delay: 600 },
      { text: "Selecting tools: Slack API, Summarizer", color: "text-muted", delay: 500 },
      { text: "Fetching messages from #engineering (last 24h)...", color: "text-muted-dark", delay: 800 },
      { text: "  Found 127 messages, 14 threads", color: "text-muted", delay: 400, indent: 1 },
      { text: "Fetching messages from #product (last 24h)...", color: "text-muted-dark", delay: 600 },
      { text: "  Found 83 messages, 9 threads", color: "text-muted", delay: 400, indent: 1 },
      { text: "Generating summaries...", color: "text-muted-dark", delay: 900 },
      { text: "  #engineering: 3 key decisions, 2 action items, 1 blocker", color: "text-brand-cyan", delay: 500, indent: 1 },
      { text: "  #product: 2 feature discussions, 1 launch update", color: "text-brand-cyan", delay: 400, indent: 1 },
      { text: "Done. Digest posted to #my-digest with action items.", color: "text-brand-emerald", delay: 500 },
    ],
  },
  {
    label: "Optimize my schedule",
    icon: Calendar,
    iconColor: "#06b6d4",
    prompt: "Analyze next week's calendar and block focus time",
    lines: [
      { text: "Parsing instruction...", color: "text-muted-dark", delay: 400 },
      { text: "Intent detected: schedule_optimize", color: "text-brand-cyan", delay: 600 },
      { text: "Selecting tools: Calendar API, Schedule Analyzer", color: "text-muted", delay: 500 },
      { text: "Loading next week's calendar...", color: "text-muted-dark", delay: 800 },
      { text: "  Mon: 6h meetings  |  Tue: 3h  |  Wed: 5h  |  Thu: 2h  |  Fri: 4h", color: "text-muted", delay: 500, indent: 1 },
      { text: "Detecting meeting-heavy days...", color: "text-muted-dark", delay: 700 },
      { text: "  Monday and Wednesday exceed 4h threshold", color: "text-brand-amber", delay: 400, indent: 1 },
      { text: "Finding focus time slots...", color: "text-muted-dark", delay: 600 },
      { text: "  Tue 9-11am  |  Thu 9-12pm  |  Fri 9-11am", color: "text-brand-emerald", delay: 500, indent: 1 },
      { text: "Creating 3 focus time blocks...", color: "text-muted", delay: 600 },
      { text: "Done. 3 focus blocks added (6h total). Conflicts: 0.", color: "text-brand-emerald", delay: 500 },
    ],
  },
];
