"use client";

import { useEffect, useRef } from "react";

/**
 * Snap-assist scroll: lets the browser handle scrolling naturally,
 * then gently snaps to the nearest section when the user stops.
 *
 * Key differences from the old approach:
 * - Never calls preventDefault() — native scroll is always active
 * - Uses scroll-idle detection instead of debounced wheel hijacking
 * - Snap is a gentle nudge, not a forced teleport
 * - User can always override the snap by continuing to scroll
 *
 * Snap completion is detected via `scrollend` (modern browsers) with
 * a generous timeout fallback, avoiding the race condition where a
 * hardcoded 500ms flag clear fires before the smooth scroll finishes.
 */

const IDLE_MS = 250; // ms of no scrolling before snap triggers
const SNAP_ZONE = 0.15; // fraction of viewport — only snap if within this distance of a boundary
const NAVBAR_OFFSET = 88;
const SNAP_TIMEOUT_FALLBACK = 1200; // generous fallback for browsers without scrollend

export default function SectionSnapScroll() {
  const idleTimerRef = useRef<number | null>(null);
  const isSnappingRef = useRef(false);
  const fallbackTimerRef = useRef<number | null>(null);

  useEffect(() => {
    // Only activate on devices with a precise pointer (mouse/trackpad)
    const finePointer = window.matchMedia("(pointer: fine)").matches;
    if (!finePointer) return;

    const hasScrollEnd = "onscrollend" in window;

    const getSections = (): HTMLElement[] =>
      Array.from(document.querySelectorAll<HTMLElement>("main > :is(section, div[id])"));

    const findNearestSectionEdge = (
      sections: HTMLElement[]
    ): { section: HTMLElement; distance: number } | null => {
      let best: { section: HTMLElement; distance: number } | null = null;

      for (const section of sections) {
        const rect = section.getBoundingClientRect();
        // Distance from this section's top to the "ideal" position (navbar bottom)
        const distance = rect.top - NAVBAR_OFFSET;

        if (best === null || Math.abs(distance) < Math.abs(best.distance)) {
          best = { section, distance };
        }
      }

      return best;
    };

    const clearFallbackTimer = () => {
      if (fallbackTimerRef.current !== null) {
        window.clearTimeout(fallbackTimerRef.current);
        fallbackTimerRef.current = null;
      }
    };

    const finishSnap = () => {
      clearFallbackTimer();
      isSnappingRef.current = false;
    };

    const snapToNearest = () => {
      if (isSnappingRef.current) return;

      const sections = getSections();
      if (sections.length < 2) return;

      const nearest = findNearestSectionEdge(sections);
      if (!nearest) return;

      const snapZonePx = window.innerHeight * SNAP_ZONE;

      // Only snap if we're close enough to a section boundary
      // (within the snap zone but not already perfectly aligned)
      if (Math.abs(nearest.distance) > 3 && Math.abs(nearest.distance) < snapZonePx) {
        isSnappingRef.current = true;

        const targetTop =
          window.scrollY + nearest.section.getBoundingClientRect().top - NAVBAR_OFFSET;

        window.scrollTo({
          top: Math.max(targetTop, 0),
          behavior: "smooth",
        });

        // Use scrollend to detect completion, with a timeout fallback
        if (hasScrollEnd) {
          const onScrollEnd = () => {
            window.removeEventListener("scrollend", onScrollEnd);
            finishSnap();
          };
          window.addEventListener("scrollend", onScrollEnd, { once: true });
        }

        // Always set a generous fallback timeout in case scrollend
        // never fires (e.g. if already at target position, or older browser)
        clearFallbackTimer();
        fallbackTimerRef.current = window.setTimeout(finishSnap, SNAP_TIMEOUT_FALLBACK);
      }
    };

    const onScroll = () => {
      // During a programmatic snap, ignore scroll events entirely —
      // they are generated by the smooth scroll animation itself,
      // not by the user. The idle timer should not restart.
      if (isSnappingRef.current) return;

      // Reset idle timer
      if (idleTimerRef.current !== null) {
        window.clearTimeout(idleTimerRef.current);
      }

      idleTimerRef.current = window.setTimeout(snapToNearest, IDLE_MS);
    };

    // A direct user gesture (wheel/touch/keydown) during a snap should
    // cancel the snap so the user retains control.
    const onUserGesture = () => {
      if (isSnappingRef.current) {
        finishSnap();
      }
    };

    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("wheel", onUserGesture, { passive: true });
    window.addEventListener("touchstart", onUserGesture, { passive: true });
    window.addEventListener("keydown", onUserGesture, { passive: true });

    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("wheel", onUserGesture);
      window.removeEventListener("touchstart", onUserGesture);
      window.removeEventListener("keydown", onUserGesture);
      if (idleTimerRef.current !== null) {
        window.clearTimeout(idleTimerRef.current);
      }
      clearFallbackTimer();
    };
  }, []);

  return null;
}
